/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.StringTokenizer;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Andre
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
        int longitud,a=0,e=0,i=0,o=0,u=0;
     String palabra,murcielago="",mostrar="",lugar="";
    public Principal() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        IngresoDatos = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProcesamientoDatos = new javax.swing.JTextArea();
        longituddeltexto = new javax.swing.JTextField();
        TotaldePalabras = new javax.swing.JTextField();
        Primerletradeltexto = new javax.swing.JTextField();
        ultimaletradeltexto = new javax.swing.JTextField();
        LetraCentraldelTexto = new javax.swing.JTextField();
        PrimerPalabra = new javax.swing.JTextField();
        UltimaPalabra = new javax.swing.JTextField();
        PalabrasPar = new javax.swing.JTextField();
        PalabrasImpar = new javax.swing.JTextField();
        RepeticionesA = new javax.swing.JTextField();
        RepeticionesE = new javax.swing.JTextField();
        RepeticionesI = new javax.swing.JTextField();
        RepeticionesO = new javax.swing.JTextField();
        RepeticionesU = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenuItem();
        GuardarComo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Copiar = new javax.swing.JMenuItem();
        Cortar = new javax.swing.JMenuItem();
        Pegar = new javax.swing.JMenuItem();
        Buscar = new javax.swing.JMenuItem();
        Reemplazar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(72, 89, 71));
        jLabel1.setText("Manejo de Cadenas ");

        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setText("Ingrese un texto o abra un archivo:");

        IngresoDatos.setColumns(20);
        IngresoDatos.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        IngresoDatos.setRows(5);
        IngresoDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(118, 142, 120)));
        jScrollPane1.setViewportView(IngresoDatos);

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setText("Longitud del Texto:");

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setText("Total de Palabras:");

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setText("Repeticiones de \"A\", \"a\" o \"á\":");

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setText("Repeticiones de \"E\", \"e\" o \"é\":");

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setText("Repeticiones de \"I\", \"i\" o \"í\":");

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setText("Repeticiones de \"O\", \"o\" u \"ó\":");

        jLabel9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel9.setText("Repeticiones de \"Ú\", \"u\" o \"ú\":");

        jLabel10.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel10.setText("Última Letra del Texto:");

        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setText("Letra Central del Texto:");

        jLabel12.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel12.setText("Primera Palabra:");

        jLabel13.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel13.setText("Palabras con cantidad de caracteres impar:");

        jLabel14.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel14.setText("Última Palabra:");

        jLabel15.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel15.setText("Palabras con cantidad de caracteres par:");

        jLabel16.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel16.setText("Primer Letra del Texto:");

        jLabel17.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(168, 108, 71));
        jLabel17.setText("TRADUCCIÓN A CLAVE MURCIELAGO:");

        ProcesamientoDatos.setColumns(20);
        ProcesamientoDatos.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        ProcesamientoDatos.setRows(5);
        ProcesamientoDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(118, 142, 120)));
        jScrollPane2.setViewportView(ProcesamientoDatos);

        longituddeltexto.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        longituddeltexto.setForeground(new java.awt.Color(72, 89, 71));
        longituddeltexto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(118, 142, 120)));

        TotaldePalabras.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        TotaldePalabras.setForeground(new java.awt.Color(72, 89, 71));
        TotaldePalabras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(118, 142, 120)));
        TotaldePalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotaldePalabrasActionPerformed(evt);
            }
        });

        Primerletradeltexto.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        Primerletradeltexto.setForeground(new java.awt.Color(72, 89, 71));
        Primerletradeltexto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(118, 142, 120)));

        ultimaletradeltexto.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        ultimaletradeltexto.setForeground(new java.awt.Color(72, 89, 71));
        ultimaletradeltexto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(118, 142, 120)));
        ultimaletradeltexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimaletradeltextoActionPerformed(evt);
            }
        });

        LetraCentraldelTexto.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        LetraCentraldelTexto.setForeground(new java.awt.Color(72, 89, 71));
        LetraCentraldelTexto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(118, 142, 120)));
        LetraCentraldelTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraCentraldelTextoActionPerformed(evt);
            }
        });

        PrimerPalabra.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        PrimerPalabra.setForeground(new java.awt.Color(72, 89, 71));
        PrimerPalabra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(118, 142, 120)));

        UltimaPalabra.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        UltimaPalabra.setForeground(new java.awt.Color(72, 89, 71));
        UltimaPalabra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(118, 142, 120)));

        PalabrasPar.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        PalabrasPar.setForeground(new java.awt.Color(72, 89, 71));
        PalabrasPar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(118, 142, 120)));

        PalabrasImpar.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        PalabrasImpar.setForeground(new java.awt.Color(72, 89, 71));
        PalabrasImpar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(118, 142, 120)));

        RepeticionesA.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        RepeticionesA.setForeground(new java.awt.Color(72, 89, 71));
        RepeticionesA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(118, 142, 120)));

        RepeticionesE.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        RepeticionesE.setForeground(new java.awt.Color(72, 89, 71));
        RepeticionesE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(118, 142, 120)));
        RepeticionesE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepeticionesEActionPerformed(evt);
            }
        });

        RepeticionesI.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        RepeticionesI.setForeground(new java.awt.Color(72, 89, 71));
        RepeticionesI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(118, 142, 120)));

        RepeticionesO.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        RepeticionesO.setForeground(new java.awt.Color(72, 89, 71));
        RepeticionesO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(118, 142, 120)));

        RepeticionesU.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        RepeticionesU.setForeground(new java.awt.Color(72, 89, 71));
        RepeticionesU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(118, 142, 120)));

        jButton1.setBackground(new java.awt.Color(72, 89, 71));
        jButton1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Procesar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(118, 142, 120));

        jMenu2.setText("Archivo");
        jMenu2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/abrir-documento.png"))); // NOI18N
        jMenuItem2.setText("Abrir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        Guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Guardar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/guardar-icono.png"))); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jMenu2.add(Guardar);

        GuardarComo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        GuardarComo.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        GuardarComo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/guardar-el-archivo.png"))); // NOI18N
        GuardarComo.setText("Guardar como");
        GuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarComoActionPerformed(evt);
            }
        });
        jMenu2.add(GuardarComo);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Editar");
        jMenu3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N

        Copiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Copiar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Copiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/copia-de-datos.png"))); // NOI18N
        Copiar.setText("Copiar");
        Copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopiarActionPerformed(evt);
            }
        });
        jMenu3.add(Copiar);

        Cortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Cortar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Cortar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/corte.png"))); // NOI18N
        Cortar.setText("Cortar");
        Cortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CortarActionPerformed(evt);
            }
        });
        jMenu3.add(Cortar);

        Pegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Pegar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Pegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pegar-objeto.png"))); // NOI18N
        Pegar.setText("Pegar");
        Pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PegarActionPerformed(evt);
            }
        });
        jMenu3.add(Pegar);

        Buscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Buscar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png"))); // NOI18N
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jMenu3.add(Buscar);

        Reemplazar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Reemplazar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Reemplazar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/reemplazar.png"))); // NOI18N
        Reemplazar.setText("Reemplazar");
        Reemplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReemplazarActionPerformed(evt);
            }
        });
        jMenu3.add(Reemplazar);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Primerletradeltexto)
                            .addComponent(ultimaletradeltexto)
                            .addComponent(LetraCentraldelTexto)
                            .addComponent(PrimerPalabra)
                            .addComponent(UltimaPalabra)
                            .addComponent(TotaldePalabras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(longituddeltexto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RepeticionesI)
                            .addComponent(RepeticionesO)
                            .addComponent(RepeticionesU)
                            .addComponent(PalabrasPar)
                            .addComponent(PalabrasImpar)
                            .addComponent(RepeticionesE, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RepeticionesA, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(202, 202, 202))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(longituddeltexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RepeticionesA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TotaldePalabras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RepeticionesE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(Primerletradeltexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RepeticionesI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ultimaletradeltexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RepeticionesO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(LetraCentraldelTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RepeticionesU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(PrimerPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PalabrasPar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(UltimaPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PalabrasImpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RepeticionesEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepeticionesEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RepeticionesEActionPerformed

    private void ultimaletradeltextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimaletradeltextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ultimaletradeltextoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

         try {
             String contenido="";
            File archivo;
           String ruta;

           JFileChooser buscarArchivo;

           buscarArchivo= new JFileChooser();

           buscarArchivo.showOpenDialog(null);

           archivo = buscarArchivo.getSelectedFile();
           ruta = archivo.getAbsolutePath();
           FileReader leer = new FileReader(ruta);
           BufferedReader lectura = new BufferedReader(leer);
           lugar= ruta;
           
             while(contenido != null){
                
                
               
                    mostrar+=contenido;
                 contenido= lectura.readLine();
                 mostrar+="\n";
           
             }
            
         } catch (FileNotFoundException ex) {
             JOptionPane.showMessageDialog(null,"Error al abrir el archivo "+ex);
         }catch (IOException ex) {
                 JOptionPane.showMessageDialog(null,"Error al abrir el archivo "+ex);
             }
         
         IngresoDatos.setText(mostrar);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void GuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarComoActionPerformed
    
        JFileChooser jfc= new JFileChooser(); 
            String direc = ""; 
            try{ 
            if(jfc.showSaveDialog(null)==jfc.APPROVE_OPTION){ 
            direc = jfc.getSelectedFile().getAbsolutePath();
            lugar=direc;
                File archivo = new File(direc);
                 FileWriter ec = new FileWriter(archivo);
                 ec.write("Palabra ingresada: ");
                 ec.write(IngresoDatos.getText());   
                 ec.write("\r\n");
                 ec.write("Clave Murcielago: ");
                 ec.write(ProcesamientoDatos.getText()); 
                 ec.close();
                 JOptionPane.showMessageDialog(null,"Archivo guardado con exito!! ");
 
            } 
            }catch (Exception ex){ 
            ex.printStackTrace(); 
            } 
    }//GEN-LAST:event_GuardarComoActionPerformed

    private void CopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopiarActionPerformed
         IngresoDatos.copy();
    }//GEN-LAST:event_CopiarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
     // Solicitar al usuario que ingrese la palabra a buscar
String buscar = JOptionPane.showInputDialog("Digite la palabra a buscar..");

// Verificar si la palabra ingresada está contenida en la cadena `palabra`
if (palabra.contains(buscar)) {
    JOptionPane.showMessageDialog(null, "La palabra " + buscar + " sí se encuentra en el texto");
} else {
    JOptionPane.showMessageDialog(null, "La palabra " + buscar + " no se encuentra en el texto");
}

    }//GEN-LAST:event_BuscarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
  
        JFileChooser jfc= new JFileChooser(); 
            String direc = ""; 
            try{ 
            if(jfc.showSaveDialog(null)==jfc.APPROVE_OPTION){ 
            direc = jfc.getSelectedFile().getAbsolutePath();
            lugar=direc;
                File archivo = new File(direc);
                 FileWriter ec = new FileWriter(archivo);
                 ec.write("Palabra ingresada: ");
                 ec.write(IngresoDatos.getText());   
                 ec.write("\r\n");
                 ec.write("Clave Murcielago: ");
                 ec.write(ProcesamientoDatos.getText()); 
                 ec.close();
                 JOptionPane.showMessageDialog(null,"Archivo guardado con exito!! ");
 
            } 
            }catch (Exception ex){ 
            ex.printStackTrace(); 
            } 
    }//GEN-LAST:event_GuardarActionPerformed

    private void CortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CortarActionPerformed
                IngresoDatos.cut();
    }//GEN-LAST:event_CortarActionPerformed

    private void PegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PegarActionPerformed
           IngresoDatos.paste();
    }//GEN-LAST:event_PegarActionPerformed

    private void ReemplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReemplazarActionPerformed
          
        String buscar = JOptionPane.showInputDialog("Digite la palabra a buscar.. ");
        String cambio = JOptionPane.showInputDialog("Digite la palabra para reemplazar..");
        
        String temporal = palabra.replace(buscar, cambio);
        
        JOptionPane.showMessageDialog(null,"La palabra "+buscar+" fue reemplazada por "+cambio +" con éxito!!");
        
        reiniciar();
        palabra = temporal;
        IngresoDatos.setText(palabra);
        
        
    }//GEN-LAST:event_ReemplazarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ProcesamientoDatos.setText("");
        palabra = IngresoDatos.getText();
        longitud = palabra.length(); 
        
         longituddeltexto.setText(String.valueOf(longitud)); 
   
         StringTokenizer contador = new StringTokenizer(palabra);
        TotaldePalabras.setText(String.valueOf(contador.countTokens()));
        Primerletradeltexto.setText( String.valueOf(palabra.charAt(0)));
      if (!palabra.isEmpty()) {
            int longitud = palabra.length();
            char ultimaLetra = palabra.charAt(longitud - 1);
            char letraCentral = palabra.charAt(longitud / 2); // Redondea hacia abajo automáticamente

            ultimaletradeltexto.setText(String.valueOf(ultimaLetra));
            LetraCentraldelTexto.setText(String.valueOf(letraCentral));
        } else {
            // Manejar el caso en que la palabra esté vacía
            ultimaletradeltexto.setText("");
            LetraCentraldelTexto.setText("");
        }
       
        
        PrimerPalabra.setText( String.valueOf(contador.nextToken()) );
        RepeticionesA.setText( String.valueOf( contarA() ) );
        RepeticionesE.setText( String.valueOf( contarE() ) );
        RepeticionesI.setText( String.valueOf( contarI() ) );
        RepeticionesO.setText( String.valueOf( contarO() ) );
        RepeticionesU.setText( String.valueOf( contarU() ) );
        String ultimaPalabra = "";  // Inicializa la variable para la última palabra
while (contador.hasMoreTokens()) { // Sigue sacando tokens hasta el final
    ultimaPalabra = String.valueOf(contador.nextToken());
}
UltimaPalabra.setText(ultimaPalabra); // Establece la última palabra
// Contador de palabras pares e impares
int pares = 0;
int impares = 0;

// Resetea el StringTokenizer para usarlo de nuevo
StringTokenizer contador2 = new StringTokenizer(palabra);

while (contador2.hasMoreTokens()) {
    String token = contador2.nextToken();
    if (token.length() % 2 == 0) {
        pares++;
    } else {
        impares++;
    }
}

// Mostrar los resultados en los JTextFields correspondientes
PalabrasPar.setText(String.valueOf(pares));
PalabrasImpar.setText(String.valueOf(impares));

       
        ProcesamientoDatos.setText(ClaveMurcielago());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LetraCentraldelTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraCentraldelTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LetraCentraldelTextoActionPerformed

    private void TotaldePalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotaldePalabrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotaldePalabrasActionPerformed
     
 public void reiniciar(){
     a=e=i=o=u=0;
     IngresoDatos.setText("");
     ProcesamientoDatos.setText("");
     longituddeltexto.setText("");
     TotaldePalabras.setText("");
     Primerletradeltexto.setText("");
     ultimaletradeltexto.setText("");
     LetraCentraldelTexto.setText("");
     PrimerPalabra.setText("");
     UltimaPalabra.setText("");
     RepeticionesA.setText("");
     RepeticionesE.setText("");
     RepeticionesI.setText("");
     RepeticionesO.setText("");
     RepeticionesU.setText("");
     PalabrasPar.setText("");
     PalabrasImpar.setText("");
     
 }
    
    public int contarA(){
        
        for(int i =0; i<longitud;i++){
           
            char letra = palabra.charAt(i);
            
            switch(letra){
                case 'A':  
                case 'a': 
                case 'á': a++; break;
            }  
        }
      
        return a;
    }
    
    public int contarE(){
        
         for(int i =0; i<longitud;i++){
           
            char letra = palabra.charAt(i);
            
            switch(letra){
                case 'E' :
                case 'e' :
                case 'é' : e++; break;
            }  
            
        }
        
        return e;
    }
    
    public int contarI(){
        
         for(int j=0; j<longitud;j++){
           
            char letra = palabra.charAt(j);
            
            switch(letra){
                case 'I' :
                case 'i' :
                case 'í' : i++; break;
            }  
        }
        return i;
    }
    
    public int contarO(){
        
         for(int i =0; i<longitud;i++){
           
            char letra = palabra.charAt(i);
            
            switch(letra){
                case 'O' :
                case 'o' :
                case 'ó' : o++; break;
            }   
        }
        return o;
    }
    
    public int contarU(){
        
         for(int i =0; i<longitud;i++){
           
            char letra = palabra.charAt(i);
            
            switch(letra){
                case 'U' :
                case 'u' :
                case 'ú' : u++; break;
            }  
        }
        return u;
    }
    
    
    public String ClaveMurcielago( ){
        for(int J =0; J<longitud;J++){
           
            char letra = palabra.charAt(J);
            
            switch(letra){
                
                case 'M':  
                case 'm': murcielago += "0"; break;
                
                case 'U' :
                case 'u' :
                case 'ú' : murcielago += "1"; break;
                
                case 'R':  
                case 'r': murcielago += "2"; break;
                
                case 'C':  
                case 'c': murcielago += "3"; break;
                
                case 'I' :
                case 'i' :
                case 'í' : murcielago += "4"; break;
                
                case 'E' :
                case 'e' :
                case 'é' : murcielago += "5"; break;
                
                case 'L':  
                case 'l': murcielago += "6"; break;
                
                case 'A':  
                case 'a': 
                case 'á': murcielago += "7"; break;
                
                case 'G':  
                case 'g': murcielago += "8"; break;
               
                case 'O' :
                case 'o' :
                case 'ó' : murcielago += "9"; break;
                
                
                default : murcielago += String.valueOf(letra); break;
                
            }  
        }
        
        return murcielago;
    }
    
  
    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Buscar;
    private javax.swing.JMenuItem Copiar;
    private javax.swing.JMenuItem Cortar;
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JMenuItem GuardarComo;
    private javax.swing.JTextArea IngresoDatos;
    private javax.swing.JTextField LetraCentraldelTexto;
    private javax.swing.JTextField PalabrasImpar;
    private javax.swing.JTextField PalabrasPar;
    private javax.swing.JMenuItem Pegar;
    private javax.swing.JTextField PrimerPalabra;
    private javax.swing.JTextField Primerletradeltexto;
    private javax.swing.JTextArea ProcesamientoDatos;
    private javax.swing.JMenuItem Reemplazar;
    private javax.swing.JTextField RepeticionesA;
    private javax.swing.JTextField RepeticionesE;
    private javax.swing.JTextField RepeticionesI;
    private javax.swing.JTextField RepeticionesO;
    private javax.swing.JTextField RepeticionesU;
    private javax.swing.JTextField TotaldePalabras;
    private javax.swing.JTextField UltimaPalabra;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField longituddeltexto;
    private javax.swing.JTextField ultimaletradeltexto;
    // End of variables declaration//GEN-END:variables
}
